server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**

        - id: auth-service
          uri: http://localhost:8083
          predicates:
            - Path=/auth/**

        - id: exam-service-exams
          uri: http://localhost:8082
          predicates:
            - Path=/exams/**

        - id: exam-service-questions
          uri: http://localhost:8082
          predicates:
            - Path=/questions/**

        - id: exam-service-topics
          uri: http://localhost:8082
          predicates:
            - Path=/topics/**

